---
# handlers file for l10n
- name: dpkg-reconfigure keyboard-configuration
  command: /usr/sbin/dpkg-reconfigure -f noninteractive keyboard-configuration

- name: dpkg-reconfigure locales
  command: /usr/sbin/dpkg-reconfigure -f noninteractive locales

- name: dpkg-reconfigure console-setup
  command: /usr/sbin/dpkg-reconfigure -f noninteractive console-setup